name: cicoffee_app
description: CICoffee Flutter Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  flutter_form_builder: ^4.0.0-pre.9
  get_it: ^5.0.1
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  flutter_speed_dial: ^1.2.5
  flutter_slidable: ^0.5.7
  intl: ^0.16.1
  duration: ^2.0.15
  flutter_sticky_header: ^0.5.0
  flutter_chips_input: ^1.9.4
  qr_flutter: ^3.1.0
  firebase_messaging: ^5.1.2
  onesignal_flutter: ^2.0.0
  device_info: ^0.4.2+10
  firebase_dynamic_links: ^0.6.3
  flutter_native_timezone: ^1.0.4
  barcode_scan: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  mobx_codegen: ^1.1.1+3


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/coffee-time.png
    - assets/facebook.png
    - assets/google.png
    - assets/qrcode.png
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Bold.ttf
